version: "3.4"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  processor:
    image: processor:latest
    restart: unless-stopped
    depends_on:
      - db
      - redis
    build: 
      dockerfile: docker/Dockerfile.processor
      context: ./
    env_file:
      - .env
    environment:
      - INDEXER_ENDPOINT_URL=https://indexer.zeitgeist.pm/v1/graphql
      - DB_HOST=db
      - POLL_INTERVAL_MS=300
      - DEBUG=hydra-processor:*
    ports:
      - "3000:3000"
    command: ["yarn", "processor:start"]

  query-node:
    image: query-node:latest
    restart: unless-stopped
    depends_on:
      - db
    build: 
      dockerfile: docker/Dockerfile.query-node
      context: ./
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "4000:${GRAPHQL_SERVER_PORT}"

  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./db/cache:/data
    environment:
      REDIS_PASS: ${REDIS_PASS}
    command: sh -c "redis-server --appendonly yes --requirepass ${REDIS_PASS}"